export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_BY_QUERY = 'GET_PRODUCTS_BY_QUERY';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_PRODUCT_RENT = 'GET_PRODUCT_RENT';

export const GET_PRODUCT_DROPDOWN = 'GET_PRODUCT_DROPDOWN';

export const IS_PRODUCT_DATA_LOADED = 'IS_PRODUCT_DATA_LOADED';

export const DATA_SUBMIT_PROGRESS = 'DATA_SUBMIT_PROGRESS';

export const IS_BOOK_MODAL_OPEN = 'IS_BOOK_MODAL_OPEN';
export const IS_RETURN_MODAL_OPEN = 'IS_RETURN_MODAL_OPEN';
